### ISSUE TITLE
Android OEM / Uhuru Mobile integration

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#167]
Hi, @btry 

How we can add these features in the backend? As policies?
We need a new key in the Agent endpoint to know if the devices is a system app.
These are features for the final review of **MobisTrust**.

- [x] Allow roaming
- [x] Allow media card
- [x] Allow FM Radio
- [x] Allow mobile line
- [x] Allow mobile voicemail
- [x] Allow speakerphone
- [x] Allow answering calls automatically
- [x] Allow voice dictation
- [x] Allow Wi-Fi
- [x] Allow NFC
- [x] Allow mobile hotspot mode and tethering
- [x] Allow create VPN profiles
- [x] Allow USB OTG mass storage
- [x] Allow SMS/MMS (send or receive)

Thanks.

**Comment by btry** [comment]
all  these policies will  be added not by "allow something" but "disable something". For consistency with existing policies. 

They'll extend the existing groups, but be ready for the merge of my pending PR which removes goups. In short each policy will have its own MQTT sub topic anf JSON will be simplified

**Comment by btry** [comment]
@rafaelje @ajsb85: **Allow create VPN profiles** <== will it also allow / disallow edition of existing profiles ?

**Comment by ajsb85** [comment]
VpnService.Builder added in API level 14
https://developer.android.com/reference/android/net/VpnService.Builder.html

**Comment by btry** [comment]
divide USB communication policy into 3 disctinct ones

https://github.com/flyve-mdm/flyve-mdm-android-agent/issues/187
