### ISSUE TITLE
Improve enrollment

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#172]
### Expected behaviour
Benefit the rules engine of Fusion Inventory

### Actual behaviour
we search a matyching computer ourselves when enrolling a devce, without using the FI import rules

After some tries I found that FI sets a session variable containing the agent ID of a created or updated computer via an inventory. ```$_SESSION['plugin_fusioninventory_agents_id']```

If the import is denied, the agent is created anyway, but the computer ID linked to  the agent is ```0```.

Then My proposal is
- enhance HTTP enrollment request handling to get a XML inventory stream, import it and find from FI agent ID then the computer ID of the device.
- simplify the next steps (creation of computer)
- ehnance the Androuid agent to send in the enrollment request  the XML inventory stream

- drop the current serial and uuid handling in the enrollment request in ther backend and the android agent.

-update unit tests of course.

**Comment by DIOHz0r** [comment]
This issue is very related with #32 so this fix will solve both cases.

**Comment by btry** [comment]
@rafaelje have a look into this and tell us if there is something blocking this change in the android agent

Moreover, note this must be merged AFTER end of november

**Comment by rafaelje** [comment]
@DIOHz0r @btry You can keep going without problem

**Comment by btry** [comment]
thanks !
