### ISSUE TITLE
Filse size option for the Item Type PluginFlyvemdmFile

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#176]
Hi, @btry and @DIOHz0r 

Could you add a key for the size of the file?

Thank you.

**Comment by ajsb85** [comment]
Fyi, the `PluginFlyvemdmPackage`.

Use the key: `filesize`

**Comment by btry** [comment]
Can you check the HTTP HEAD verb works first, when you try to download the file ?

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html (section 9.4)

I think this is better than maitnaining a value in the DB. This is a metadata of the file itself.

**Comment by ajsb85** [comment]
No, it's not to download the file, this is to get all files, the list don't have the key filesize. But in the app list appear.

**Comment by ajsb85** [comment]
Example of the package

```JSON
[
    {
        "id": 2,
        "name": "com.uberspot.a2048",
        "alias": 2048,
        "version": 2,
        "version_code": 20,
        "icon": "iVBORUVORK5CYII=",
        "filename": "/var/www/public/glpi/files/var/www/public/glpi/filesflyvemdm/package/0/59f33f8f84a16_59f33f83a0e786.9244290156fa7aa5ed741_com.uberspot.a2048_20.apk",
        "filesize": 633567,
        "entities_id": 0,
        "dl_filename": "59f33f83a0e786.9244290156fa7aa5ed741_com.uberspot.a2048_20.apk",
        "plugin_orion_tasks_id": 0,
        "parse_status": "parsed",
        "links": [
            {
                "rel": "Entity",
                "href": "https://dev.flyve.org/glpi/apirest.php/Entity/0"
            }
        ]
    },
```

**Comment by ajsb85** [comment]
You can see the `filesize`

But take a look in the file:

```JSON
    {
        "id": 8,
        "name": "Icon.png",
        "source": "14/597babff83c94_Icon.png",
        "entities_id": 14,
        "version": 1,
        "links": [
            {
                "rel": "Entity",
                "href": "https://dev.flyve.org/glpi/apirest.php/Entity/14"
            }
        ]
    },
```

**Comment by ajsb85** [comment]
Example of usage

![files-100](https://user-images.githubusercontent.com/663460/32791903-57077a94-c962-11e7-9409-7b95fc2cce8d.jpg)

**Comment by btry** [comment]
I'll add he file size in a new DB column.

**Comment by ajsb85** [comment]
@btry Thank you

**Comment by ajsb85** [comment]
@btry Any news?

**Comment by btry** [comment]
Not yet. If this is blocking for you let me know.
