### ISSUE TITLE
Force display in search task return error

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#189]
Hi, @btry 

Example request:

`{{base_url}}/search/{{PluginAlias}}Task/?forcedisplay[0]=2&forcedisplay[1]=3&forcedisplay[2]=4&forcedisplay[3]=5&forcedisplay[4]=6&forcedisplay[5]=7&uid_cols&range=0-1000`

```JSON
[
    "ERROR",
    "ID is forbidden along with 'forcedisplay' parameter.; view documentation in your browser at https://dev.flyve.org/glpi/apirest.php/#ERROR"
]
```

**Comment by btry** [comment]
Hi

The message is clear: displaying this ID is not allowed. This is explicitly set in the search options for this itemtype. This is also  true for ID 5 and 6.

Why do you need to show them ?

**Comment by btry** [comment]
see here: https://github.com/flyve-mdm/flyve-mdm-glpi-plugin/blob/develop/inc/task.class.php#L658

**Comment by ajsb85** [comment]
Ok, so never force display when the nodisplay = 1 👍

**Comment by btry** [comment]
As usual, please provide a use case to understand why it is needed to change a search option.

The existence of a field is not sufficient to give it a search option. Also in this case, nodisplay is self explanatory.

**Comment by btry** [comment]
Hi

I think we can close this issue with "wont fix" label.
