### ISSUE TITLE
Remove Orion 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#199]
Hi, @btry 

Could you extend the Flyve MDM Plugin and the Orion Plugin to integrate with scan features without use "Orion" words in the code of the Flyve MDM Plugin?
https://git.io/vF5W6

The idea is to integrate other scan system in the future, without add code in this plugin.

**Comment by btry** [comment]
Hi

I cannot remove these words. the code you found is the minimum required to make both plugins work together.

**Comment by btry** [comment]
Discussed on Telegram: no need to remove change the code. Other scanners can be easily added.
