### ISSUE TITLE
Document upgrade of the plugin

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#212]
We need to document the steps to upgrade the plugin,  from a release to an other, and from a  revision to an other revision (develop branch only)

**Comment by Naylin15** [comment]
Hi, @btry 

Could you please help me and review if these steps are the right ones to update the plugin?

Thank you

From one release to another
* Download the new version of the plugin
* Disable the installed version first
* Overwrite the files with the new version
* Go in the directory glpi/plugins/flyvemdm
* Run ```php tools/cli_install.php``` 

From one revision to another (develop branch)
* Disable the installed version first
* Go in the directory glpi/plugins/flyvemdm
* Use ```git pull``` to update your local branch
* Run ```php tools/cli_install.php```
