### ISSUE TITLE
Probable egg and chicken problem Package /  Task

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#221]
Create a fleet
apply a app deployment policy
check the remove_on_delete flag is set
try to remove the policy applied to the fleet

Before deleting the object of type task, the backend will remove the app deployment policy. It will  then create a app removal  policy. Then the task will still have a policy but will be deleted.

To be checked.

If this actuallky happens:
in  the pre_deleteItem() of PluginFlyvemdmTask I think we need to disable remove_on_delete flag of app deployment policies.

To implement this we need ti add a new method in the interface of policies: deleteTask() receiving the task object as argument.
The policy, depending on its type will ignore the action, or do necessary actions to avoid creation of a replacmeent policy. Example in app deployment policy::unapply().

**Comment by DIOHz0r** [comment]
Hi, I'm not getting your point

> Then the task will still have a policy but will be deleted.
What do you mean with this sentence?.... I tested it and the installation task was deleted from DB then a new one for removalapp with a value of "N/A" (the package hasn't have a name) was created. 

I don't get the chicken/egg problem. If the agent gets the policy to remove the app and if the app doesn't exist it should be ignored, but if exist it would be removed or am I wrong?.

**Comment by DIOHz0r** [comment]
After some discussions the policies will be refactored to handle this problem between the policies and tasks loop. The code of policies will use the apply method to execute their own logic and trigger the add/update tasks.

The first refactor of this policies can be seen with the PR #364

**Comment by btry** [comment]
With latest developements, It is clear for me that the problem is solved.
