### ISSUE TITLE
Packages uploads name broken

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/glpi-plugin#232]
### Expected behaviour
Show the name of the the package on the module

### Actual behaviour
When a package is uploaded the name of it gets lost, at the list there are showed only the ID from the database, also if the package is used in a policy it can't be deleted until if the name value in DB is blank.

### Environment Details
- GLPi version: 9.2
- Flyve MDM version: 2.0.0-dev

### Steps to reproduce the behaviour

1. Upload a package file.
2. Save the details of it.
3. Show the list of packages uploaded.

### Screenshots, backtraces or logs
![imagen](https://user-images.githubusercontent.com/1426313/33567316-1e1f8798-d8f9-11e7-8b6f-1af2529089da.png)

**Comment by btry** [comment]
To sum up:
the package name is not broken. It is updated by t he automatic action in charge of apk parsing.

I tried to implement the solution I submitted yesterday, but unfortunately the search engine calls getSpecificValueToDisplay() only if the column name has a value longer than 0.. then this ruins my idea.

Other proposal:
- put the package name in a new column: package name
- use name as a field the user may fill like any other itemtype. If the user chooses to leave teh field empty then the display with the ID will persist, but this is the normal behaviour in GLPI. 

This way the user can name his packages. Currently he simply cannot.
