### ISSUE TITLE
How-tos and development documentation

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#235]
Hi, @Naylin15 

Change the name "Wiki" to "How-tos" and add these articles; and add the sub menu items to the Development section. If these pages does not exist, please, create an issue and request it. 👍 

**How-tos**

- [x] How to install
- [x] How to use
- [x] Use Cases
- [x] How it works
- [x] How to contribute
- [x] How to Translate

**Development**

- [x] Code documentation
- [ ] Code coverage
- [ ] Test report

**Comment by ajsb85** [comment]
Hi, @btry @DIOHz0r 

To-Do:

- [ ] Code coverage
- [ ] Test report

**Comment by btry** [comment]
This is an extra task related to builds. We may create an orphan branch or a repo for these data.

A repo looks good : one branch per sub project, and configure CI to push there the reports. We may also setup automatic tags when a build occurs for a tagged revision.

Any thought ?


Le 11 janvier 2018 12:05:06 GMT+01:00, Alexander Salas Bastidas <notifications@github.com> a écrit :
>Hi, @btry @DIOHz0r 
>
>To-Do:
>
>- [ ] Code coverage
>- [ ] Test report
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/flyve-mdm/glpi-plugin/issues/235#issuecomment-356901945

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by ajsb85** [comment]
Hi, @btry 

The idea is to push the report of the develop branch in a folder into the gh-pages branch.

References: #249 & #250
