### ISSUE TITLE
Reset password policy need send string

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#242]
### Expected behaviour
when sent this policy to the agent need add a string, this string is the new password

### Actual behaviour
This policy sent a boolean value

this is the proposal format:
{ "passwordReset": "newPassword", "taskId": "2"}

**Comment by DIOHz0r** [comment]
This issue was resolved by error on the PR #165 at https://github.com/flyve-mdm/glpi-plugin/blob/81207aee8f5de61fda7a2ca3e51983a639f22f11/install/installer.class.php#L1419
