### ISSUE TITLE
Installation Wizard 

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#262]
### Expected behaviour

The Installation Wizard requires in the DBMS access for Mosquitto to change the name of the DB tables

### Actual behaviour
The DBMS access for Mosquito has the wrong name for the DB tables

### Environment Details

- HTTP server version:
- GLPi version: 9.2.1
- Flyve MDM version: 2.0.0-dev
- FusionInventory version: 9.2-1.0
- Mosquitto version: 1.4.14
- Mosquitto's auth plugin  version:

**Comment by btry** [comment]
see #263
