### ISSUE TITLE
Agent enrollment fail with a deleted devices

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#269]
Now when I try to enroll the device can do it:

This is my workflow:

# On the Dashboard:

- Go to flyve.org
- login with my account
- Remove some device
- Add request a new invitation

# On the Agent:

Tested on a wipe device with android 6.0

- Wait for the invitation email
- Click on deeplink
- Play to enroll
- Fill the required fields
- Click to enroll

At first time I got a message that says:
`FusionInventory can't be created`

If I make click again got this message:
`You don't have permission to make this action`

**Comment by btry** [comment]
Hi

I think the first message is ```FusionInventory agent not created```. The message ```FusionInventory can't be created``` does not exists in the code.

**Comment by DIOHz0r** [comment]
This issue couldn't be reproduced, the plugin is adding the device as new one every enrollment action.
