### ISSUE TITLE
Add ID for List searchOption endpoint

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/glpi-plugin#276]
### Expected behaviour
The List searchOption endpoint should show the ID of itemType

### Actual behaviour
The List searchOption endpoint does not show the IDs

### Environment Details
- GLPi version: 9.2
- Flyve MDM version: 9.2

### Steps to reproduce the behaviour
1. Request to search items, any ItemType from PluginFlyvemdm

**Comment by btry** [comment]
The official documentation of GLPI says the IDs of the search options are returned.

https://github.com/glpi-project/glpi/blob/9.2/bugfixes/apirest.md#list-searchoptions.

I'll take a look and check if I see a regression
