### ISSUE TITLE
Search Items endpoint does not show the fields in the correct order

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/glpi-plugin#277]
### Expected behaviour
In search Items endpoint the first field should be the ID and the second the name,  as indicated by the documentation of glpi for forcedisplay parameter

https://dev.flyve.org/glpi/apirest.php#search-items

### Actual behaviour
In search Items endpoint does not show the fields in the correct order

### Environment Details
- GLPi version: 9.2
- Flyve MDM version: 9.2

### Steps to reproduce the behaviour
1. Request to search items, any ItemType from PluginFlyvemdm

**Comment by DIOHz0r** [comment]
GLPI core assigns by default the field 1as the name of the item, so ID is going to be used as field number 2.
