### ISSUE TITLE
Get unrollment message for every email

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#285]
#### Observed Results:
Testing the unenroll policy with the new topics, always get `{"unenroll":"now"}` on the agent with any email, these are the steps to reproduce the bug:

- Enroll device with email "A"
- Send unenroll policy from dashboard
- Get unenroll policy on the agent

- Enroll a device with email "B"
- get unenroll policy

- Enroll a device with email "C"
- get unenroll policy

**Comment by btry** [comment]
Do you mean that the unenroll MQTT message is sent to all agents ?

**Comment by rafaelje** [comment]
@btry I don't know if is send to all agents at the same time but everytime that I enroll one device with the same account the first mqtt message is /2/agent/Unknown/Command/Unenroll I'll check this issue in deep with @DIOHz0r

**Comment by btry** [comment]
OK, then I think I got it. 

We need to check if the unenroll mesage us persistent. If yes, after unenrollment, and assuming you enroll again the same serial number, then unenrollment message is not reset then you receive it again. 

This may  be a regression related to the removal of mqtt queuing.

Please confirm you enroll several times the same device (with the same serial)

**Comment by rafaelje** [comment]
@btry yes I'm enrolled with the same device (with the same serial) many times but with another device too with different serial I want to be sure to reproduce with both scenarios

**Comment by btry** [comment]
I think we should reset Mosquitto on the development platform. The PR to remove the queuing feature may have an impact.

**Comment by rafaelje** [comment]
Fine please let me finish this PR https://github.com/flyve-mdm/android-mdm-agent/pull/279 to implement this change on the backend
