### ISSUE TITLE
Create a Policy/removeApp topic with message empty

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#294]
#### Observed Results:

- Create a new fleet
- Create a new Files
- Add policy "Deploy File"
- Remove the policy "Deploy File"
- The plugin automatically adds a new policy "Remove file" but the value of the message send to the agent is empty

<img width="1206" alt="captura de pantalla 2018-01-31 a la s 3 52 10 p m" src="https://user-images.githubusercontent.com/4085091/35644245-cfc867ee-069e-11e8-91b8-b81d1fd7e06a.png">

#### Expected behavior:

- The message of the "Remove file" policy will be the document to remove

**Comment by DIOHz0r** [comment]
Hi, FYI I'm working with this issue since last Friday.

**Comment by btry** [comment]
It seems some code was lost (a rebase maybe ?)

**Comment by DIOHz0r** [comment]
I think it was lost probably with the change for the queued task. I'm taking advantage of this issue to add new unit tests and some code refactoring

**Comment by btry** [comment]
Possible. This pointed a lack of unit tests on this policy. Now this is fixed :) thanks :)
