### ISSUE TITLE
Enhance UI for policies edition / creation

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#308]
#### Observed Results:
Creation of a policy
![image](https://user-images.githubusercontent.com/14139801/35920377-fb57901e-0c17-11e8-9329-a45ee8039206.png)

Update of a policy
![image](https://user-images.githubusercontent.com/14139801/35920367-f4ccbe72-0c17-11e8-85cd-e127c41a14b4.png)

  
#### Expected behavior:

Something more clean. I think it is time to add twig in PluginFlyvemdmPolicy::showValueInput() method (overriden in many children classes)

**Comment by btry** [comment]
related to #493

**Comment by DIOHz0r** [comment]
Changes merged but the issue was not closed.
