### ISSUE TITLE
Display problem in entity configuration 

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#344]
The inheritance of entity settings is not handled correctly in the UI
  
#### Observed Results:

![image](https://user-images.githubusercontent.com/14139801/36491660-9836c918-172b-11e8-9307-69cce80429fd.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/14139801/36491703-b3d46ba8-172b-11e8-88da-ac5a6b698570.png)

**Comment by DIOHz0r** [comment]
Hi, could you indicate the steps or the environment to reproduce this error? I've tried on my local develop environment without that '-2' values

**Comment by btry** [comment]
- Create an entity child of the root entity.
- In the root entity, setup any text to fill one or several fields
- edit  the sub entity and view the support informations. You should see the value -2 which has a special meaning. I think we need improvements here to "catch" this value and display the value of the parent entity.

**Comment by DIOHz0r** [comment]
I did your steps and I don't get those values, I'm getting the root entities values 
![imagen](https://user-images.githubusercontent.com/1426313/36787687-54c67878-1c61-11e8-8bba-a88a2ab60d03.png)

**Comment by btry** [comment]
Indeed, I think the entity I viewed was created when the plugin was disabled or something like that. I found this while working on an other plugin.

Let's close it.
