### ISSUE TITLE
DB scheme for development section

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#348]
#### Expected behavior:
It is required to add a DB scheme to the development section on the website

**Comment by DIOHz0r** [comment]
Hi @Naylin15,

This is the current scheme of the DB for the version 2.0.0 of the plug-in.

![imagen](https://user-images.githubusercontent.com/1426313/42227036-8e62e2c4-7eae-11e8-8b72-96df8e70b621.png)

**Comment by btry** [comment]
oh.... have fun modelizing the relations :D

**Comment by Naylin15** [comment]
Thanks @DIOHz0r 

I'll add it in the project site 👍

**Comment by Naylin15** [comment]
Solved in #625 

Closing this issue
