### ISSUE TITLE
getFromDBByQuery deprecated in GLPI 9.3

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#365]
at least one PR fails with GLPI 9.3 (currently branch master) because getFromDBByQuery is deprecated.

We need to find all calls to this method and replace them by $DB->request(), in order to make tests work again. 

This is high priority because other tests on other PRs depend on this (and not so hard)

**Comment by DIOHz0r** [comment]
There are also the following deprecated functions:

- countElementsInTable
- autoName
- getEntitiesRestrictRequest

**Comment by btry** [comment]
Feedback of the discussion with the GLPI team : 

getFroDBByQuery() has the special property of failing if the query returns several rows. Deprecating it is OK but no equivalent is available in GLPI. We may use DB::request() but we need to add logic to handle cases where the number of returned rows is not 1.

We encounteer this case several times in Flyve MDM.

We agreed I develop a new methid in CommonDBTM getFromDBByRequest(), and having an array as argument.

I'll do that, next I'll replace our colls to getFromDBByQuery().

@DIOHz0r if you start the replacement of other deprecated methods you identified, please share it. Either I push my commits to your branch, either I do a distinct PR (then having 2 PRs fixing the same issue).

**Comment by DIOHz0r** [comment]
OK, I'll wait for your change first meanwhile I'm solving the remove application issue
