### ISSUE TITLE
SSL certified is expired

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#368]
#### Observed Results:

With this MQTT URL mqdev.flyve.org I got this error message on the Android agent:

```
javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Mon Feb 26 23:59:59 GMT+00:00 2018 (compared to Thu Mar 15 21:17:57 GMT+00:00 2018)
03-15 21:17:57.223 E:
```

#### Expected behavior:

Connect with the agent with SSL certified

**Comment by DIOHz0r** [comment]
Hello,

I don't have access to the server for domain mqdev.flyve.org, @btry could you help me with this please?

**Comment by btry** [comment]
solved yesterday.
