### ISSUE TITLE
MQTT daemon diagnosis

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#370]
If the daemon fails to run we need to provide information about the failure, to help the admin to solve the problem

**Comment by btry** [comment]
* check the correct instanciation of the mqtt client for the deamon. It the instanciation fails, do not try to attach a handler instance.

**Comment by DIOHz0r** [comment]
With the code refactor on PR #524 the instantiation of the client is now registered on log files.

**Comment by btry** [comment]
PR merged, closing
