### ISSUE TITLE
Documentation migration

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#373]
#### Observed Results:
In this issue I'll be adding / updating the progress for the migration of the documentation to Read the Docs

  
#### Expected behavior:
Migrate the documentation to the Readthedocs platform

References:

* [Read the docs](http://docs.readthedocs.io/en/latest/index.html) 
* [Sphinx](http://www.sphinx-doc.org/en/master/index.html)

**Comment by Naylin15** [comment]
Update:

Here is a link to the doc-test repo: 

http://doc-tests.readthedocs.io/en/latest/#

It now has the sphinx_rtd_theme, the same as GLPI documentation

**Comment by Naylin15** [comment]
Update:

Installation information added

**Comment by Naylin15** [comment]
Update:

How it works, update and getting started information added

**Comment by Naylin15** [comment]
Update:

Use cases information added

**Comment by Naylin15** [comment]
Update:

Rest Api information added
Started the customization, now the sidebar has the plugin logo and Flyve MDM name

![Logo](https://user-images.githubusercontent.com/30867977/37855003-9a882b9e-2ec3-11e8-9875-39634fc28bc7.png)

**Comment by Naylin15** [comment]
Update

the configuration information was added and the build was customized with flyve logo and colors

![Flyve MDM](https://user-images.githubusercontent.com/30867977/37916630-5b0824dc-30ea-11e8-935c-d37368afbe22.png)

**Comment by Naylin15** [comment]
Update:

New link:  http://flyvemdm-doc.rtfd.io/

**Comment by Naylin15** [comment]
Update:

The policies and features documentation was added issue #378 

The M2M specifications information was added

**Comment by Naylin15** [comment]
Update:

Contributing documentation added

**Comment by Naylin15** [comment]
Hi, @ajsb85 

All documentation of the plugin is now on read the docs

Link: http://flyvemdm-doc.rtfd.io/

**Comment by Naylin15** [comment]
To do:

Add documentation about unenrollment in getting started section

**Comment by Naylin15** [comment]
Update:

Unenrollment and delete agent information added in getting started section

**Comment by Naylin15** [comment]
Update:

Improvements to the getting started section, added:
* List to steps
* How to assign an Agent to a Fleet
* How to add policies
* General redaction

**Comment by Naylin15** [comment]
Update:

Starting the change in gif images for better understanding, add numbers to sequence and click highlight

Progress: 

[Create Fleet image](http://flyvemdm-doc.readthedocs.io/en/latest/getting-started/index.html#create-your-fleet)

**Comment by Naylin15** [comment]
Update:

Gif images in the getting started section were changed, the new gifts were made from mov files

**Comment by Naylin15** [comment]
WIP:

Updating the contribute section

**Comment by Naylin15** [comment]
Update:

Contribute section updated

**Comment by Naylin15** [comment]
Update:

Policy's list updated, added link to compatibility matrix

**Comment by Naylin15** [comment]
Hi @ajsb85 @btry @DIOHz0r 

The documentation on read the docs is updated, I want to unpublish the articles in the project site and add a direct link to RTD for the How tos section, like Ravada does for their documentation and finish the migration

**Comment by btry** [comment]
Ok for me !

**Comment by Naylin15** [comment]
Hi, this issue can be closed

I the documentation is hosted on read the docs and the link is on both project site and readme
