### ISSUE TITLE
show policies feedback

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#383]
Add UI in the plugin to monitor how are applied the policies o n the devices

- a new tab on the agents to show the list of task statuses.
- update the agents tab to show a bar with several colors, each per status
    - statuses specific to some policies (deployment) should be merged into a single color

**Comment by DIOHz0r** [comment]
Just to confirm if this issue, the PR #381 has some of this features but no the one about colors, Must this issue keep open?

**Comment by btry** [comment]
keep open please
