### ISSUE TITLE
_sessions folder is huge

### ISSUE THREAD

**Issue by jmpolvera** [flyve-mdm/glpi-plugin#417]
in the glpi/files/_sessions/ folder there are a huge amount of files.

Is there a solution to reduce the number of files regularly? I think it will saturate the file system inodes in the long term

What do you recommend?

**Comment by btry** [comment]
Hi

GLPI has a automatic action to cleanup the session folder.

![image](https://user-images.githubusercontent.com/14139801/38608312-4c696a38-3d7b-11e8-8d3a-0bd609d8b559.png)

set **Run mode** to CLI to execute  this action from the cron you already configured.
![image](https://user-images.githubusercontent.com/14139801/38608401-8793e7aa-3d7b-11e8-84a9-3fc0e608428c.png)
