### ISSUE TITLE
Add debug setting

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#424]
#### Observed Results:
Add debug setting to select between the URLs of the beta and production version of the Agent

  
#### Expected behavior:
New debug setting

**Comment by btry** [comment]
By default the production version must be used, we might add a setting in cli_install.php script to easily isntall the plugin in development mode and choose the development URL too :fireworks:

**Comment by Naylin15** [comment]
Update:

A dropdown was added to select between the MDM Agent Play Store URL and the MDM Agent Beta testing to change the url in the current entity

![debug](https://user-images.githubusercontent.com/30867977/38758987-aadb1b08-3f41-11e8-8dbf-c6751392ca8d.png)

**Comment by Naylin15** [comment]
Update:

The cli install --dev is ready, it now changes the download url for the beta testing in root entity

Also, changed the dropdown for a text area

![captura de pantalla 2018-04-17 a la s 5 34 58 p m](https://user-images.githubusercontent.com/30867977/38899418-c4ed4a76-4265-11e8-943a-97aee2824af0.png)

**Comment by btry** [comment]
Great !

If you create an entity child of the root entity, the text field shold be empty and have a green text telling its value is inherited, right ?

**Comment by Naylin15** [comment]
No, it shows the green text but the text area shows the value of the root entity

![captura de pantalla 2018-04-18 a la s 9 02 22 a m](https://user-images.githubusercontent.com/30867977/38933565-59309a36-42e7-11e8-9d93-25d089adaef3.png)

**Comment by btry** [comment]
Can you change this to have the same behavior as the other fields ?

Also, I notice you put a textarea. I think a text field (single line) is more appropriate.

**Comment by btry** [comment]
I thought you would do the reverse.

I think that if you click on save, then the fields will be saved in DB, and the inheritance will be broken. This is transparent as long the entity and its parent share the same values. But if a sub-sub-entity shall have inheritance from it grand-parent entity, there will be a problem.

**Comment by Naylin15** [comment]
Hi @btry I changed the text area and the display, now it doesn't show the values from root but when clicking on save it saves empty values, keeping the green message

Child entity
![captura de pantalla 2018-04-18 a la s 4 52 51 p m](https://user-images.githubusercontent.com/30867977/38957562-fb942914-4328-11e8-9e50-792db808b06b.png)

Root entity
![captura de pantalla 2018-04-18 a la s 4 53 50 p m](https://user-images.githubusercontent.com/30867977/38957623-18dc0bb8-4329-11e8-89b9-9860ba377846.png)
