### ISSUE TITLE
PluginFlyvemdmEntityconfig update

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/glpi-plugin#426]
#### Observed Results:

I am sending to update the property 'agent_token_life' of the itemtype PluginFlyvemdmEntityconfig with the id. But I find the following problem:

The backend is returning a 200, which I interpret as a correct answer. But the reality is that this value is not being updated.

![captura de pantalla 2018-04-12 a la s 1 14 03 p m](https://user-images.githubusercontent.com/19965590/38698157-19648176-3e62-11e8-8354-192edf4dc00e.png)
![captura de pantalla 2018-04-12 a la s 1 14 09 p m](https://user-images.githubusercontent.com/19965590/38698158-198a1b16-3e62-11e8-8499-392fbe1b45af.png)
![captura de pantalla 2018-04-12 a la s 1 13 55 p m](https://user-images.githubusercontent.com/19965590/38698160-19b6a78a-3e62-11e8-992c-ffe852f5fda4.png)

  
#### Expected behavior:

Update the value if possible, otherwise return an error message

**Comment by btry** [comment]
Yes, why not

**Comment by btry** [comment]
There is a choice there : 

- ignore the properties you're not allowed to change and actually change those where you have rights (then silent failure)
- make the whole request fail

Indeed, the dashboard needs a notification. OK to trigger an error.
