### ISSUE TITLE
Please merge translations from Transifex

### ISSUE THREAD

**Issue by p-bo** [flyve-mdm/glpi-plugin#436]
Thanks :)

**Comment by btry** [comment]
Hi

OK I'll update development branch

**Comment by btry** [comment]
Hi

The development branch is updated. However a lot of new strings were created and all languages were below the 70% translation ratio limit. I updated french. All other languages need an update from translators.

**Comment by p-bo** [comment]
What about translations of Flyve MDM components itself - are source strings on Transifex in sync with devel?

**Comment by btry** [comment]
Hi
The android apps (mdm ag ent and inventory agent) should be up to date, the only need contributions for translations !

Thank you for your contribution !

**Comment by p-bo** [comment]
Done for android mdm and inventory agent. What about admin dashboard for Android, for web. And iOS apps? Supposing that Win mobile and Blackberry are death platforms so worthless to translate, aren't they?

**Comment by btry** [comment]
Hi

Development for windows will target windows 10 for IoT and tablets. There is nothing to translate yet as the development did not start.

For blackberry, we target MDM oriented features of this manufacturer. We will support only devices based on Android as the previous OS is dead. No development done yet.

Then there is nothing to translate yet for these 2 projects. Effort is for now focused on improvements on Android + development for iOS support.
