### ISSUE TITLE
Move policies definition from installer to dedicated files 

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#449]
The installer becomes really big with the array of policies. I think we should split this array into smaller ones. 

- one file per category
- a subdirectory to store all files. 
- code to read this sub directory and load all .php files.

**Comment by btry** [comment]
This is not urgent. No milestone set.

**Comment by DIOHz0r** [comment]
I was thinking to do the same for the policies on the inc directory
