### ISSUE TITLE
GH pages build fails

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#452]
There is a check for external links, but this check fails
https://travis-ci.org/flyve-mdm/glpi-plugin/builds/370284864

```
- ./_site/howtos/contribute.html
  *  External link https://support.teclib.com failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Peer certificate cannot be authenticated with given CA certificates
```

I guess the package cal-certificates is missing in the VM. Try to add ```apt install ca-certificates```.

**Comment by ajsb85** [comment]
Hi, @Naylin15 already solved this issue in other repositories.

**Comment by DIOHz0r** [comment]
Hmm.. this issue wasn't closes with the PR.... the last build for gh-pages got a success status
