### ISSUE TITLE
Improve QR code for invitations

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/glpi-plugin#473]
**Is your feature request related to a problem? Please describe.**
The QR code has a lot of information to scan and it generates a condensed image with a large number of pixels making it difficult to scan specially when some devices hasn't have the property to focus their camera.

After a lot of tests I'd found that a minimal image size for solve this issue is 488px × 488px and the precision of  the code could be the lowest available.

**Describe the solution you'd like**
Make the image bigger on the invitation and the deeplink page to make the invitation more easy to scan. 

**Describe alternatives you've considered**
The other solution would be to reduce the quantity of information used on the QR code to generate less pixels

**Comment by btry** [comment]
Maybe changing the parameters of this call ?

https://github.com/flyve-mdm/glpi-plugin/blob/develop/inc/invitation.class.php#L323

**Comment by btry** [comment]
We may also increase the error correction

https://tcpdf.org/examples/example_050/
