### ISSUE TITLE
Bad word Enroll in source language

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#481]
**Describe the bug**
In many places we use the word ```enroll``` ... which is wrong. this must be ```enrol```

**Expected behavior**
enrollment => enrolment
enroll => enrol
and so on...

**Additional context**
The source language must be updated

**Comment by DIOHz0r** [comment]
I've found that both spelling are correct the problem is the region used (USA or outside), there are around 240 occurrences of the 'enrol' string on the plugin, so this change is going to be massive. Should we really need to do this right now or for another version?

Source: http://grammarist.com/spelling/enrol-enroll/

**Comment by btry** [comment]
You found a good resource, better than the one I used before opening this issue. As we should use English US as source language, your resource shows we may close this issue as invalid (and this is a good news).

**Comment by btry** [comment]
You found a good resource, better than the one I used before opening this issue. As we should use English US as source language, your resource shows we may close this issue as invalid (and this is a good news).

**Comment by btry** [comment]
You found a good resource, better than the one I used before opening this issue. As we should use English US as source language, your resource shows we may close this issue as invalid (and this is a good news).

**Comment by btry** [comment]
You found a good resource, better than the one I used before opening this issue. As we should use English US as source language, your resource shows we may close this issue as invalid (and this is a good news).
