### ISSUE TITLE
Geolocation marks

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/glpi-plugin#499]
**Describe the bug**
The marks of the locations of the devices do not appear

**To Reproduce**
1. Select a device
2. Click on geolocation
3. See error

**Expected behavior**
see the marks of the locations without problems

![captura de pantalla 2018-05-14 a la s 3 58 38 p m](https://user-images.githubusercontent.com/19965590/40020303-b5fd06c0-578f-11e8-8786-75f25052f204.png)

**Screenshots**
![captura de pantalla 2018-05-14 a la s 3 50 12 p m](https://user-images.githubusercontent.com/19965590/40020313-bb6f32c2-578f-11e8-83a5-3e6f1ab4a454.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 66.0.3359.139

**Comment by Gianfranco97** [comment]
Error 500 


![captura de pantalla 2018-05-18 a la s 12 08 41 p m](https://user-images.githubusercontent.com/19965590/40245846-be6e1c2e-5a94-11e8-845a-32553cddabb1.png)

**Comment by btry** [comment]
Please show the whole request and request body of the faulty request. Without them it will be hard to reproduce

**Comment by Gianfranco97** [comment]
![captura de pantalla 2018-05-18 a la s 12 24 58 p m](https://user-images.githubusercontent.com/19965590/40246413-af47d878-5a96-11e8-8829-4bb022894aaf.png)
![captura de pantalla 2018-05-18 a la s 12 25 40 p m](https://user-images.githubusercontent.com/19965590/40246414-af74b186-5a96-11e8-9b75-1c4d6c51aeaf.png)
![captura de pantalla 2018-05-18 a la s 12 25 46 p m](https://user-images.githubusercontent.com/19965590/40246415-afaddb6e-5a96-11e8-8e44-4d0730123f25.png)
![captura de pantalla 2018-05-18 a la s 12 25 58 p m](https://user-images.githubusercontent.com/19965590/40246416-afe459c8-5a96-11e8-9c74-f4867bcdd2c3.png)

**Comment by Gianfranco97** [comment]
```
Request URL: https://dev.flyve.org/glpi/plugins/flyvemdm/ajax/geolocation.php?computers_id=273&beginDate=Fri+Apr+06+2018+19%3A48%3A48+GMT-0400+(-04)&endDate=Thu+May+10+2018+15%3A02%3A01+GMT-0400+(-04)
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 185.10.252.222:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by Gianfranco97** [comment]
```
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en,es-419;q=0.9,es;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Cookie: undefined=7hl6ls01i3lv23fi61vt8qrss0; glpi_30b8c5aa4d3246b20f0eae2e09f476fa_rememberme=%5B%222%22%2C%22%242y%2410%24hGgVX2evo6AlHMVKLfrcJ.JZ7vFh8ilizbG01NrKvToZrkrbGgOZ6%22%5D; glpi_30b8c5aa4d3246b20f0eae2e09f476fa=9lpqbir3969l0mudp4cjdnbj84
DNT: 1
Host: dev.flyve.org
Pragma: no-cache
Referer: https://dev.flyve.org/glpi/plugins/flyvemdm/front/agent.form.php?id=274
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
X-Requested-With: XMLHttpRequest
```

**Comment by Gianfranco97** [comment]
```
computers_id: 273
beginDate: Fri Apr 06 2018 19:48:48 GMT-0400 (-04)
endDate: Thu May 10 2018 15:02:01 GMT-0400 (-04)
```

**Comment by btry** [comment]
I think the format of the date un the URL is the cause of the error. Let's invewrigate tis week

**Comment by DIOHz0r** [comment]
Errors 500 are normally problems related with a bad configuration on the server like a .htaccess rule. I'll check this issue

**Comment by btry** [comment]
we should reopen. See the comment from @DIOHz0r in the PR
