### ISSUE TITLE
Code refactor needed

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#503]
The same code appears in 2 different places (see #502 , the foreach loop)
- PluginFlyvemdmFile::post_updateItem()
- PluginFlyvemdmPackage::post_updateItem()

We need to create 
- an abstract class, parent of both classes named ```PluginFlyvemdmDeployable```
- which implements an interface named ```PluginFlyvemdmDeployableInterface```

Maybe some more code may be mutualized.

/cc @Naylin15 if she want to do it.

**Comment by DIOHz0r** [comment]
I think we could close this issue because the were a lot of refactor and the deployable class was created.
