### ISSUE TITLE
Wrong policies availables

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#511]
Please check these policies available:

<img width="1212" alt="captura de pantalla 2018-05-18 a la s 11 30 35 a m" src="https://user-images.githubusercontent.com/4085091/40243803-2b4fa67e-5a8f-11e8-80d2-ff18512cd1ec.png">

**Comment by btry** [comment]
Please add a commit per policy to remove in #495 I created this PR in this purpose.
