### ISSUE TITLE
Allow display all fields from PluginFlyvemdmTask

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/glpi-plugin#513]
**Is your feature request related to a problem? Please describe.**
When request a searchItems to PluginFlyvemdmTask does not allow to show all the fields in this table

for example to request a listSearchOptions to PluginFlyvemdmTask fields 6 and 7 are set to not show, the uid field shows that these fields are not obtained from the relationship with other tables

![captura de pantalla 2018-05-21 a la s 10 54 58](https://user-images.githubusercontent.com/8787200/40314085-74913624-5ce5-11e8-88f3-533610fdfca9.png)

**Describe the solution you'd like**
Set in listSearchOptions value nodisplay on false to fields 6 and 7 or all field that don't come from a relationship with another table

**Comment by hectorerb** [comment]
Maybe that you suggest is right, but at this moment I need to know the itemtype and ID to manage the task

**Comment by btry** [comment]
OK, then let's just remove the nodisplay property.
