### ISSUE TITLE
Create unit tests in some class's methods

### ISSUE THREAD

**Issue by ingluife** [flyve-mdm/glpi-plugin#564]
Hi, @flyve-mdm/backend-development.

**Is your feature request related to a problem? Please describe.**
Currently, in the code-coverage report there is missing unit test in some class or class method.
**Describe the solution you'd like**
Create the test methods corresponding to everyone missing.

This is the coverage report:

![image](https://user-images.githubusercontent.com/17582750/41875456-ec664f76-7898-11e8-829d-6f7f21fd63ca.png)

**Comment by DIOHz0r** [comment]
Test merged but issue wasn't closed
