### ISSUE TITLE
Some policies are not applying

### ISSUE THREAD

**Issue by jfreakazoid** [flyve-mdm/glpi-plugin#569]
**Describe the bug**
Policies seems to apply but not in the reality. Just some of them are applied properly (BlueTooth, Password and FlightMode), the rest, nothing happen despite that the polices appears in the Policies TAB in the mobile agent.  Remote lock and wipe, are not working neither.

**To Reproduce**
N/A

**Expected behavior**
Well... the policies should apply. 

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Linux Debian 9
 - Browser Mozilla Firefox. 
 - Version 60.0.2

**Smartphone (please complete the following information):**
 - Device: Huawei MYA L03
 - OS: Android 6.0
 - Browser Chrome
 - Version

**Additional context**
Agent version Flyve MDM 2.33.0, build 1763. Ping, GPS Location and Inventory working properly.

**Comment by btry** [comment]
Hi

What are the brand, model of your device ? Which version of Android is running on it ?

If the policies are marked applied in the mdm agent then I think that the issue is when the mdm agent applies the policies.

If you're able to run adb logcat on your device, then maybe there are some logs related to those failures. 

/cc @rafaelje

**Comment by DIOHz0r** [comment]
@rafaelje  could you confirm if "Flyve MDM 2.33.0, build 1763" is the last working version?

**Comment by jfreakazoid** [comment]
Hi @btry sorry for my late reply. Right now I'm performing an adb logcat to figure out if I can find something. However, let me show you what's appears in the GLPI interface related with the Policies. Some of the are cancelled by itself and some of ther are pending. 

![task](https://user-images.githubusercontent.com/10604088/42329821-3f5e1da8-8037-11e8-9bd5-90e145836de7.png)

Cheers

**Comment by jfreakazoid** [comment]
Hi again @btry ... After checking my logs, look what is showing me when I try to apply a policy. 

07-05 10:28:23.055  5893  5893 E AndroidRuntime: FATAL EXCEPTION: main 
07-05 10:28:23.055  5893  5893 E AndroidRuntime: Process: org.flyve.mdm.agent, PID: 5893 
07-05 10:28:23.055  5893  5893 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.flyve.mdm.agent.room.entity.Policies.value' on a null object reference 
07-05 10:28:23.055  5893  5893 E AndroidRuntime: 	at org.flyve.mdm.agent.receivers.CustomPhoneStateListener.onCallStateChanged(CustomPhoneStateListener.java:44)

07-05 10:28:23.228  1024  1266 E InputDispatcher: channel '3bf5650 org.flyve.mdm.agent/org.flyve.mdm.agent.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed

Now I update the agent version to 2.38.0, build 1815.

Cheers

**Comment by btry** [comment]
Hi

Good ! I think we can do something with this backtrace.

@rafaelje @DIOHz0r can you have a look on this please ?

**Comment by jfreakazoid** [comment]
@btry Thank you very much. I really appreciate it. If you need something else from my side, don't hesitate to let me know. 

Cheers.

**Comment by rafaelje** [comment]
Hello @jfreakazoid to execute these policies the app should be installed on system you can review how to install like system on this link:

http://flyve.org/android-mdm-agent/howtos/installation

**Comment by btry** [comment]
We will add some additional information on screen to warn about requirements of policies
- MDM agent  needs to be installed as system app
- MDM agent needs root access

**Comment by jfreakazoid** [comment]
@rafaelje OK Rafael, thank you very much. I didn't know about it. I will do it and I'll give you my feedback asap. 

Saludos.

**Comment by jfreakazoid** [comment]
Well guys... the only problem that I see is the imperative need for rooting the device. Related to warranty effects is quite chaotic.

**Comment by btry** [comment]
Hi

You need to root the device or you need a partnership with a manufacturer to install the mdm agent as a system app. This gives to the mdm agent the power to apply more policies. If the mdm agent does not has privileges, only a subset of policies will work.

**Comment by jfreakazoid** [comment]
@btry Well copied. Thank you very much.

**Comment by btry** [comment]
#721 should help to determine if a policy will work in your context. We also think it would be interesting to feedback the privileges of the mdm agent to the backend
