### ISSUE TITLE
Prepare Simcard management in GLPI

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#57]
Simcard inventory from agents to GLPI.

First: implement simcards in GLPI
Next: use them in this plugin.

**Comment by btry** [comment]
Implementation waiting for review in GLPI: 

https://github.com/glpi-project/glpi/pull/2311

Next step: implement it in FusionInventory

**Comment by ajsb85** [comment]
Hi, @btry 

The glpi-project/glpi#2311 is merged.

Whats about the FI Agent?

Thanks.

**Comment by btry** [comment]
In FI this is WIP

**Comment by ajsb85** [comment]
@btry ok, Could you add here the reference?

**Comment by btry** [comment]
We need to ask to Guillaume; he is working on it.

**Comment by ajsb85** [comment]
Hi, @g-bougard 

Any news about this feature on FI?

Thanks.

**Comment by g-bougard** [comment]
Hi @btry & @ajsb85 
yes, actually I have a WIP through netinventory task (network inventory using snmp) for Digi based devices in [FIA PR #382](https://github.com/fusioninventory/fusioninventory-agent/pull/382).

We have also historical MODEMS support for few systems, but specs are not fully supported and related perl modules need to be upgraded. Btw actually we don't have any request for that.

**Comment by grego1981** [comment]
It would very good if it could update and connect with the GLPI SIM card module which is very good.  https://github.com/pluginsGLPI/simcard

**Comment by btry** [comment]
Hi
@grego1981 the simcard plugin is no longer needed. In GLPI 9.2, simcards are a native compoment (like memoty, power supply, ...).

I'm curently preparing a small update to handle IMSI field for GLPI 9.2.1.

In the mean time, there is work in progress in FusionInventory to handle simcards.

The plugin is considered as end of life now; and your suggestion is already on its way ;)

**Comment by btry** [comment]
Simcards are handled in GLPI
FusionIvnentory can now import basic information about them.

There will be improvements over time; but the feature exists. Closing this issue.
