### ISSUE TITLE
Dashboard in GLPI UI: garbage in graphs

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#573]
Hello

![image](https://user-images.githubusercontent.com/14139801/42084569-5286392c-7b8e-11e8-96b6-e29adb93e3c0.png)

We have some entries in horizontal axis which are garbage from old way to get OS name.

There is no bar (because of 0 devices ?) We should **maybe** filter out these entries.

**Comment by DIOHz0r** [comment]
I've updated the dev server and still having the same problem. @ingluife this is the same issue #560 the labels on the javascript are still repeating please check this as soon as possible.

**Comment by DIOHz0r** [comment]
```js


                  $(function() {
                     var chart_devices_per_operating_system_version = new Chartist.Bar('#devices_per_operating_system_version', {
                        labels: ['Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Jelly Bean (Android 4.1)', 'KitKat (Android 4.4)', 'Lollipop (Android 5.1)', 'Marshmallow (Android 6.0)', 'Nougat (Android 7.0)', 'Nougat (Android 7.1.1)', 'Oreo (Android 8.0)'],
                        series: [9, 1, 2, 1, 1, 1, 2, 1]
                     }, {
                        low: 0,
                        showArea: true,
                        width: '100%',
                        height: '300',
                        fullWidth: true,
                        distributeSeries: true, plugins: [Chartist.plugins.tooltip()]});
                     chart_devices_per_operating_system_version.on('draw', function(data) {
                        if(data.type === 'bar') {
                           data.element.animate({
                              y2: {
                                 begin: 300 * data.index,
                                 dur: 500,
                                 from: data.y1,
                                 to: data.y2,
                                 easing: Chartist.Svg.Easing.easeOutQuint
                              }
                           });
                        }
                     });
                  });
```

Here you can see that the label array repeat the strings

**Comment by ingluife** [comment]
Hi, @flyve-mdm/backend-development.

What branch is in the dev.flyve? This branch is updated?

The question is becouse i am in the develop branch in my local, and i am not see the issue.

This my interface:

![image](https://user-images.githubusercontent.com/17582750/42099692-1d9c1fda-7b8c-11e8-95c6-5b44fdf1ab9e.png)

This is the javascript corresponding:

![image](https://user-images.githubusercontent.com/17582750/42099771-5b8064dc-7b8c-11e8-9e4d-8eaaf6038ceb.png)

**Comment by DIOHz0r** [comment]
I have checked the version on dev server and it wasn't up to day cause there was an stash file, now the site is showing the correct graph

**Comment by btry** [comment]
thank you !
