### ISSUE TITLE
Create specification of json inventory

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#58]
Related to: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/27

**Comment by btry** [comment]
We defined to use XML specification from fusionInventory, ported to JSON

**Comment by ajsb85** [comment]
Hi, @btry 

We are changing the XML specifications from FI to JSON based on https://google.github.io/styleguide/jsoncstyleguide.xml

**Comment by btry** [comment]
We need to handle JSON in FusionIvnentory (I began something but Have things more urgent for now). Dont drop too quickly XML. Use a mechanism to switch the mode in the agent

**Comment by ajsb85** [comment]
@btry Ok, the work in the libraries will be done today, we use these features to collect anonymous usage data.

**Comment by ajsb85** [comment]
Hi, @btry 

This is the proposal from the iOS inventory library:
https://gist.github.com/ajsb85/72e683910c856936ffb72ff9fc1e9c19


This is the proposal from the android inventory linbrary:
https://gist.github.com/ajsb85/894ab3b78051760c2d5a9011f7e986f4

We will create arrays in every category in the proposal of the iOS.
And we will change some keys in camelCase to lowercase in the proposal for Android.

Regards.

**Comment by btry** [comment]
We require the specs are the same for any target OS.

To keep comaptibility with more complex hardware like a (real) computer, we need arrays for most devices. Even BIOSes may exist in several isntances in a single device. 

* I suggest we rely on current XML specs to determine if an item may be fed back several times (dual sim, several drives, ...). 

* It is better to have something to separate words in an identifier. Either camelCase either underscore. Again, to have a smooth transition from XML, let's see if underscore is already used. If not, OK for camelCase, If there are underscores, let's keep them in JSON specs. I'm against lowercase to anticipate the future, even if we find that currently identifiers are only single word.

**Comment by ajsb85** [comment]
In the specs of FI we have `USERID` and `KERNEL_VERSION` tag names, its hard to normalize automatically, we will create lowercase in this moment for the tags name as USERID.

We will work together with the team of FI for a renormalization of the next version of FI.

The work is in progress to release today a version of the JSON body payload for the @chollimabot.

**Comment by DIOHz0r** [comment]
Reviewing this issue we don't handle the inventory file in JSON format because FusionInventory only works with XML and its specification. I think this issue could be closed because it is not related to the backend.

**Comment by btry** [comment]
We need to discuss about that. For now, we may close the issue.
