### ISSUE TITLE
Linters Warning and Errors

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#626]
#### Observed Results:
The tests on [TravisCI are failing](https://travis-ci.com/flyve-mdm/glpi-plugin/builds/79493557)
![captura de pantalla 2018-07-19 a la s 3 34 28 p m](https://user-images.githubusercontent.com/30867977/42965945-827525cc-8b69-11e8-8c0f-bf8aaa98f002.png)
![captura de pantalla 2018-07-19 a la s 3 34 12 p m](https://user-images.githubusercontent.com/30867977/42965946-82ab52d2-8b69-11e8-9dd3-db729a5a8c09.png)

  
#### Expected behavior:
Fix the warnings and errors

**Comment by DIOHz0r** [comment]
Changes merged
