### ISSUE TITLE
Commit message history

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#658]
Hi, @btry and @DIOHz0r 
There are malformed commit message in `develop` and `master`.
And the master branch is not up to date with the RC.

![image](https://user-images.githubusercontent.com/663460/43153549-dcc52dfe-8f71-11e8-8cb4-479e7c82d393.png)

![image](https://user-images.githubusercontent.com/663460/43153533-d175ce86-8f71-11e8-97e1-d3286f75ed53.png)

**Comment by btry** [comment]
Hi this is too late. People use got to download the project. Rewriting git history on master and develop would negatively impact all of them. 

It is up to us to be more careful before merging to develop.

**Comment by btry** [comment]
About master. Its head must match the latest tag. Currently it is 2.0.0-rc.1.
