### ISSUE TITLE
I did not receive email to validate account using plugin demo mode 

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/glpi-plugin#672]
**Describe the bug**
Hi @flyve-mdm/backend-development 

when I try to register a user using [demo-mode](https://github.com/flyve-mdm/demo-model) the user registers correctly but I'm not receiving the email to validate the account.

I'm do a request to this end point https://dev.flyve.org/glpi/apirest.php/PluginFlyvemdmdemoUser

This is the response:
`{"id":680,"message":"You are not allowed to change the invitation token life"}`

![captura de pantalla 2018-08-01 a la s 14 35 19](https://user-images.githubusercontent.com/8787200/43541363-3b134e6e-9598-11e8-92c0-4e243fb7d57f.png)

![captura de pantalla 2018-08-01 a la s 14 23 56](https://user-images.githubusercontent.com/8787200/43541361-3afa12aa-9598-11e8-817d-e0ea1792c782.png)

**To Reproduce**
1. Go to https://dev.flyve.org/dashboard/signUp
2. Complete the form
3. Click on 'Register'
4. Shows notification message successfully registered user
5. Redirect to https://dev.flyve.org/dashboard/validateAccount
6. I'm not receiving the account validation email

**Comment by btry** [comment]
The demo mode is abandoned, the demo for version 2.0 will be handled without this plugin.

**Comment by btry** [comment]
hi I think we can close his issue, right ?
