### ISSUE TITLE
Section for develop and master branch doc

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#678]
#### Observed Results:
Currently we are only displaying the documentation for the develop branch, we need to add a space for the documentation on master branch

  
#### Expected behavior:
To have the documentation for changes in both develop and master branch for the project site

**Comment by ajsb85** [comment]
Hi, @Naylin15 
We need also to versioning the documentation and reports.

**Comment by Naylin15** [comment]
Hi, @DIOHz0r 

The new structure for the documentation will be like this, for the develop and master branch
```
development
   dev-version
     code-documentation
     coverage
   latest-version
     code-documentation
     coverage
```

**Comment by Naylin15** [comment]
New proposal:

```
development
   coverage
     master
     develop
   code-documentation
     master
     develop
```

**Comment by Naylin15** [comment]
Hi, @ajsb85 

After discussing the multi versioning with @hectorerb and @Gianfranco97  the proposal to handle several versions of the code-documentation and coverage, will be to create the documentation and store it in a folder named as the tag, send it to gh-pages and add the tag number in a whitelist, all this from CI

On gh-pages, from the whitelist, it will be created all the links to the respective documentation according to the tag, therefore, the final structure will be as follows:

```
development
   coverage
     develop
     tag 1.x
     tag 2.x
   code-documentation
     develop
     tag 1.x
     tag 2.x
```

**Comment by Gianfranco97** [comment]
Or 
```
development
   coverage
     develop
     release
       1.x
        2.x
   code-documentation
     develop
     release
        1.x
     release 
       2.x
```

**Comment by Naylin15** [comment]
Solved in #682 

The dropdown for development will be updated only for the version folders in the support directory, since the develop and master folders will be always defined. The update will be made through a script and a yml list to generate the new links to the folders

Final structure 

```
development
   coverage
     develop
     support
       1.x
       2.x
   code-documentation
     develop
     support
       1.x
       2.x
```

Closing this issue

**Comment by Naylin15** [comment]
The CI is not updating the coverage in the correct folder, it's updating it in the old structure

**Comment by Naylin15** [comment]
This issue has been fixed, the documentation is being updated correctly
