### ISSUE TITLE
Generate code documentation with ApiGen

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/glpi-plugin#694]
#### Expected behavior:
Use ApiGen to create the code documentation of the project

 Reference:

* [ApiGen](https://github.com/ApiGen/ApiGen)

**Comment by Naylin15** [comment]
There are issues with the other dependencies when trying to install apigen, when using the command to install

```composer require apigen/apigen --dev```

It starts giving this ouput

![captura de pantalla 2018-08-15 a la s 10 04 25 a m](https://user-images.githubusercontent.com/30867977/44154163-18b26644-a078-11e8-9061-a97571981a0b.png)

**Comment by DIOHz0r** [comment]
I'm reopening this issue because locally the documentation was able to work but on CI it fails because a possible conflict with another vendor library

![imagen](https://user-images.githubusercontent.com/1426313/44535905-2f7a9480-a6c9-11e8-867c-c081a23b7e87.png)
