### ISSUE TITLE
unclear documentation for enrollment use case

### ISSUE THREAD

**Issue by btry** [flyve-mdm/glpi-plugin#702]
**Describe the bug**
On this page

https://flyvemdm-doc.readthedocs.io/en/latest/use-cases/enrollment-process.html

a user was lost reading the enrollment use case, see https://forum.glpi-project.org/viewtopic.php?id=164766

Indeed, the page is unclear. It does not say anything about the microservice. We need to enhance fix it.

**To Reproduce**
1. find a user trying to understand the enrollment process
2. until this user scratches his head

**Expected behavior**
The user shall understand immediately

**Screenshots**
![image](https://user-images.githubusercontent.com/14139801/44470674-9e54e080-a62a-11e8-83ff-78fc7cf8a95a.png)

**Comment by Naylin15** [comment]
Hi,

I added more information regarding the deeplink on this PR [#5](https://git.io/fAkFU)

**Comment by Naylin15** [comment]
Hi,

This issue can be closed, the PR [#5](https://git.io/fAkFU) has been merged
