### ISSUE TITLE
Problem with Instantiation of the agent

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#718]
**Describe the bug**

https://flyvemdm-doc.readthedocs.io/en/latest/use-cases/enrollment-process.html#instantiation-of-the-agent

When creating a new Instantiation of the agent

the return has this format:

Response code: 201

```
{
    "id": 382,
    "message": "XML has been imported succesfully!"
}
```

but the documentation says that should be:

```
{
   "id": "17"
}
```

**Comment by Naylin15** [comment]
Solved in [#6](https://github.com/flyve-mdm/doc/pull/6)
