### ISSUE TITLE
Fatal error during install a maximum execution time

### ISSUE THREAD

**Issue by lebowski42** [flyve-mdm/glpi-plugin#729]
**Describe the bug**
Trying to install the plugin runs into ""

During Install: Fatal error: Maximum execution time of 30 seconds exceeded

**To Reproduce**
Install glpi 9.3.1 and fusioninventory 9.3+1.1. Clone flyve-mdm plugin into plugin directory. and run `composer install --no-dev`

Go to Setup -> Plugins and hit "install" for fusion inventory. When hitting "Install" for flyvemdm you get the error message below

Error message

( ! )  Fatal error: Maximum execution time of 30 seconds exceeded in  /usr/local/apache2/htdocs/glip/glip/vendor/zendframework/zend-cache/src/Storage/Adapter/AdapterOptions.php  on line 180
--

1 | 0.0006 | 374288 | {main}(  ) | .../plugin.form.php:0
2 | 0.4030 | 1522704 | Plugin->install( string(1) ) | .../plugin.form.php:47
3 | 0.4169 | 1524216 | plugin_flyvemdm_install(  ) | .../plugin.class.php:705
4 | 0.4170 | 1526240 | PluginFlyvemdmInstaller->install(  ) | .../hook.php:41
5 | 24.3930 | 2935792 | PluginFlyvemdmInstaller->createPolicies(  ) | .../installer.class.php:134
6 | 32.5508 | 3011848 | PluginFlyvemdmPolicy->add( array(15), ???, ??? ) | .../installer.class.php:341
7 | 32.5512 | 3011848 | PluginFlyvemdmPolicy->filterValues( true ) | .../commondbtm.class.php:1040
8 | 33.5672 | 3012944 | PluginFlyvemdmPolicy->getSearchOptionByField( string(5), string(11), ??? ) | .../commondbtm.class.php:3882
9 | 33.5672 | 3012944 | PluginFlyvemdmPolicy->searchOptions(  ) | .../commondbtm.class.php:3810
10 | 33.5673 | 3012944 | PluginFlyvemdmPolicy->rawSearchOptions(  ) | .../commondbtm.class.php:3533
11 | 33.5683 | 3014448 | __( string(6), string(8) ) | .../policy.class.php:106
12 | 33.5683 | 3014448 | Zend\I18n\Translator\Translator->translate( string(6), string(8), ??? ) | .../autoload.function.php:112
13 | 33.5684 | 3014448 | Zend\I18n\Translator\Translator->getTranslatedMessage( string(6), string(5), string(8) ) | .../Translator.php:356
14 | 33.5684 | 3014448 | Zend\I18n\Translator\Translator->loadMessages( string(8), string(5) ) | .../Translator.php:442
15 | 33.5685 | 3014544 | Zend\Cache\Storage\Adapter\Apcu->getItem( string(62), ???, ??? ) | .../Translator.php:609
16 | 33.5686 | 3014544 | Zend\Cache\Storage\Adapter\ApcuOptions->getReadable(  ) | .../AbstractAdapter.php:338

![grafik](https://user-images.githubusercontent.com/3740660/44998917-9ea19400-afb9-11e8-8482-a99c87fc98e4.png)

**Comment by btry** [comment]
Hi,

If you have this error, use the CLI installer instead of the glpi UI.
