### ISSUE TITLE
Problem With Qr Code On emails

### ISSUE THREAD

**Issue by spinaldf** [flyve-mdm/glpi-plugin#730]
Hi, I have problem to receive the QR Code Image on My emails Client. I check header of email.
I have problem to open on some browsers and clients of emails.

Example code:

```
<p><a href=3D=
";http://flyve.org/deeplink/?data=3DaHR0cHM6Ly9kZW1vLWFwaS5mbHl2ZS5vcmcvYXB=
pcmVzdC5waHBcO3p2MFdMRXh6VDVrWVpTbVJYWkZuRUhqbDEyTFlUTUU5N3FNRUdkekpcOzQzM2=
U1OGVhMmY3NDhjMzUwMDkwODljNjIzZTIwYmFhZjlmMGRjMTRjZGNjOWNhODAxYTFlMzYwOGJiO=
TJjMzdcO1w7XDtcOw=3D=3D" ;>http://flyve.org/deeplink/?data=3DaHR0cHM6Ly9kZW=
1vLWFwaS5mbHl2ZS5vcmcvYXBpcmVzdC5waHBcO3p2MFdMRXh6VDVrWVpTbVJYWkZuRUhqbDEyT=
FlUTUU5N3FNRUdkekpcOzQzM2U1OGVhMmY3NDhjMzUwMDkwODljNjIzZTIwYmFhZjlmMGRjMTRj=
ZGNjOWNhODAxYTFlMzYwOGJiOTJjMzdcO1w7XDtcOw=3D=3D</a></p><p><img src=3D";cid=
:#091faab5-86cc5719-5b892e78a34a48.62989438#" ; alt=3D";Enroll QRCode" titl=
e=3D";Enroll QRCode"></p>
```

**Comment by Ebesan** [comment]
Hi!
I'm also having problem related to emails and enrollment. Issue is that the deeplink provided via email invitation won't work. It isn't even recognized as link in the email. I tried to copy the link to browser and open it, but it just opens blank flyve page. 
Tested with GLPI version 9.3.0 and Flyve MDM plugin version v2.0.0-rc.2
Tested with phones Samsung xCover3 and Huawei Honor lite 7.
![screenshot_20180907-142847 1](https://user-images.githubusercontent.com/40197190/45216906-b74bcb80-b291-11e8-87d4-f762496413af.png)
![screenshot_20180907-142857 1](https://user-images.githubusercontent.com/40197190/45216909-b87cf880-b291-11e8-9040-2fdda4bc4943.png)

**Comment by btry** [comment]
Hi

We found an issue in our production instance of deeplink service.

**Comment by Gianfranco97** [comment]
Done, service running

Ref: 
- https://github.com/flyve-mdm/deeplink/pull/33
- https://github.com/flyve-mdm/deeplink/pull/34

**Comment by DIOHz0r** [comment]
The email URL hasn't been checked and fixed

**Comment by DIOHz0r** [comment]
@spinaldf, Could you please share us the full url for your glpi api?. For that go to Setup -> General -> API

**Comment by DIOHz0r** [comment]
The URL and QR code image are generated without a problem, beside I realized on your first message some extra HTML code in the body email that is not pressent on the original template of the plugin so another software is changing the email content. 

Some email clients as Thunderbird, Outlook, Gmail, etc. parse the content of the emails for "security" reasons, in this cases we can't do too much because that is not part of our plugin code, those are email client behavior.
