### ISSUE TITLE
Application name is null

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#748]
**Describe the bug**
When adding a new application on Dev environment the tag deployApp on the MQTT message come with a null value

**To Reproduce**
1. Go to Flyve
2. Click on General -> Package
3. Add new application
4. Create a fleet and add the applications
5. Add the fleet to the device
6. Open the Android Agent Activity -> Log

**Expected behavior**
Get the deployApp with the package name of the app or the name of the app

**Screenshots**
![screenshot_1536962255](https://user-images.githubusercontent.com/4085091/45577911-68330700-b84c-11e8-9c5d-c6c50e23809a.png)

**Comment by btry** [comment]
I think this may happen when a package is deleted from the db and a MQTT message is generated. Let's check from the task id  which package id  is attached to the task, then trycto reproduce

**Comment by btry** [comment]
Other possible case, deploying  a package not yet parsed

**Comment by DIOHz0r** [comment]
I think this issue is happening in the branch release 2.0, the issue was replicated with an empty name on the demo server and rafael tested on dev, but for develop branch the app name is filled locally.

**Comment by DIOHz0r** [comment]
Update for the previous comment, 

I uploaded another apk and I got the correct name
![imagen](https://user-images.githubusercontent.com/1426313/45648346-4f1d9680-ba96-11e8-9127-2381783eeac5.png)

I noticed that the previous apk hasn't had an alias and updated its values, after that I update the policy to remove it the name was filled.
![imagen](https://user-images.githubusercontent.com/1426313/45648426-82f8bc00-ba96-11e8-9a0f-dde0b467b9ff.png)

**Comment by btry** [comment]
Then I'm suspecting that null comes from a package not yet parsed by the automatic action.

We need to filter out those apps in the dropdown. Similar case happens when we update a package to a newer version.

**Comment by DIOHz0r** [comment]
New update... the null value comes from a problem on the web dashboard because they don't sent the alias value. A new "status" will needed in this case as you said for filter those not parsed apps .

**Comment by btry** [comment]
Here is my proposal to solve the issue:
- disable sending a mqtt message when we deploy a package on a notifiable when the name of the app is null
- trigger a refresh of the mqtt message when the package version code of the package is updateds (post_UpdateItem())
- when we upload an updated version of an apk, then we should reset the package name and versin code in db. The automatic actin parsing apks will re-update them.

This way a user may deploy an app before it is parsed. Once parsed the mqtt message will be sent. If the package is updated (uyplaod of a new apk) then the code will refresh the  mqtt message
