### ISSUE TITLE
Lost connectivity Cert Path Validator Exception

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#750]
Lost connectivity CertPathValidatorException: Trust anchor for certification path not found.

**Describe the bug**
When @DIOHz0r add a fleet the MQTT connection close and after that now the agent show this error message:

```
09-17 16:28:24.195 21107-21107/org.flyve.mdm.agent E/org.flyve.mdm.agent: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
09-17 16:28:24.196 21107-21107/org.flyve.mdm.agent E/org.flyve.mdm.agent: │ Thread: main
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ MqttModel.showDetailError  (MqttModel.java:639)
09-17 16:28:24.197 21107-21107/org.flyve.mdm.agent E/org.flyve.mdm.agent: │    FlyveLog.e  (FlyveLog.java:118)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ (506) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by DIOHz0r** [comment]
We have to confirm this but it looks like a problem on the agent and not for the plugin.

**Comment by rafaelje** [comment]
I'll check this solution on the agent, but is a random issue

https://danielme.com/tip-android-35-https-y-certificados/

**Comment by DIOHz0r** [comment]
These are the message from the MQTT broker's log...

1537216101: OpenSSL Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
1537216101: OpenSSL Error: error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure

**Comment by rafaelje** [comment]
I was talking with @DIOHz0r and I remember that this problem happened with Dev environment the first time when enroll the device connect and working fine but if the device disconnect and try to reconnect again fail, I think @btry fix something with the certification on the server did you remember that?

**Comment by btry** [comment]
Yes I remember:

the issue disappeared when I fixed a mis configuration related to TLS in Mosquitto. I don't have all details in mind because this is quite old. If I remember correctly, the certificate presented by the server to the clients did not contained all certificates to build the trust chain.

That's why I suggested to use openssl s_client to check if the trust chain is correct.

**Comment by DIOHz0r** [comment]
This problem has been solved, the reason of the error was because the certificate used on the mqtt broker server had and incompleted content, the server doesn't had the full certificate chain.
