### ISSUE TITLE
Try to enroll with some email and report activity in other

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/glpi-plugin#779]
**Describe the bug**
I try to enroll my own device with the last agent but always get a message "Invitation is not pending" the email was new, the agent was installed new, but the behavior is I try to enroll the agent with the Email A but all the information was reported on the Email B, checking the Agent Payload the information email is correct has information of the email A

![captura de pantalla 2018-10-11 a la s 8 03 30 p m](https://user-images.githubusercontent.com/4085091/46840540-8fb8b900-cd91-11e8-8b94-5aad1ce1397f.png)

**Comment by btry** [comment]
Hi,

I think my work in progress to change the invitation use case will solve your issue. You probably have 2 user accounts with the same email address.

**Comment by DIOHz0r** [comment]
I checked the info on demo and both invitation were in done status, so it looks like a issue on the dashboard. @Gianfranco97 you must check this because the log data is was for ***ri@hi2.in and it's showed for ***dbx@hi2.in

**Comment by btry** [comment]
we need to finish this PR

https://github.com/flyve-mdm/glpi-plugin/pull/770

**Comment by rafaelje** [comment]
Was a problem on the MDM Android Agent the invitation token was not updated with QR scan
