### ISSUE TITLE
Image suffix of invitation email is .png but contains a JPG file

### ISSUE THREAD

**Issue by abma** [flyve-mdm/glpi-plugin#781]
**Describe the bug**
the innovation mail "[GLPI] You have been invited to join Flyve MDM" contains an image as attachment. The filename is somehash.png. When viewing the image the type is JPEG, quality: 90, subsampling OFF

**To Reproduce**
1. Send innovation mail in glpi
2. Open attachment mail and check the type

**Expected behavior**
either the file type should be changed to PNG or the file suffix should be changed to .jpg so it matches its content.

I'm currently using Flyve Mobile Device Management 2.0.0-rc.2 and GLPI 9.3.1.

**Comment by DIOHz0r** [comment]
Hello, have you really check the file type? all the files are generated with PNG functions and formats the the [file ](https://linux.die.net/man/1/file) command on Linux shows that the files generated are PNG.

![imagen](https://user-images.githubusercontent.com/1426313/47109182-97f27780-d21b-11e8-921f-dc61a2dcd5ab.png)

**Comment by DIOHz0r** [comment]
I can confirm the issue, for some reason the file is changed during the email sending process.
![imagen](https://user-images.githubusercontent.com/1426313/47110253-4b5c6b80-d21e-11e8-9a3b-85204fd1b957.png)

@btry you could fix this issue with the same PR #770

**Comment by btry** [comment]
I think the patch should be in GLPI. The plugin generates a PNG file, and we give to GLPI a hash to identify the file (itemtype document) to tell GLPI that the picture must be attached to the email. 

The convertion to JPG occurs in GLPI, probably in the library phpmailer itself.

I choosed to use PNG format to avoid loss of quality and maximize QR scan. This conversion is not expected.

**Comment by DIOHz0r** [comment]
Hello, This issue was solved but not closed and I can't close it. Please do it.
