### ISSUE TITLE
Invitations never change the status

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#828]
Invitations always as pending
https://dev.flyve.org/glpi/plugins/flyvemdm/front/invitation.php

![image](https://user-images.githubusercontent.com/663460/50178146-03cc8b80-0304-11e9-9d02-a1e6fee55e73.png)

**Comment by DIOHz0r** [comment]
![imagen](https://user-images.githubusercontent.com/1426313/50178384-b851b780-02da-11e9-9cac-48662cd3315e.png)
If this option is enabled the invitation status is never changed so this is a wanted behaviour
