### ISSUE TITLE
APK parser does not works

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#831]
APK for testing:

https://github.com/flyve-mdm/android-mdm-agent/releases/download/2.0.0-rc.7/org.flyve.mdm.agent_2018-12-17_205621-fcm-release.apk

![image](https://user-images.githubusercontent.com/663460/50180940-4d6ca480-030b-11e9-8689-ee9ac073887b.png)

**Comment by btry** [comment]
I did a test today, and it works fine. Logs show that the task is actually runnin every minute as expected.
