### ISSUE TITLE
Add MDM Agent type (Android, iOS, Uhuru...) in Agent screen on the GLPI UI

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#839]
Hi, @flyve-mdm/backend-development 

Please rename MDM Type key into OS Name, as used by the FusionInventory procotol.
And show it in these screens (Agent screen, Computer screen)

Examples from the Inventory Report:
```XML
<OSNAME>iOS</OSNAME>
<OSNAME>Android</OSNAME>
```

![image](https://user-images.githubusercontent.com/663460/50257956-d06e2780-03fd-11e9-8a71-c5dc44415c27.png)
--------------------------
![image](https://user-images.githubusercontent.com/663460/50258156-a8cb8f00-03fe-11e9-921b-80f4500d4bdf.png)

**Comment by btry** [comment]
Hi,

The mdm type is related to toe operating system of the mobile device, but this is NOT the operating system. The operating system is saved in the GLPI core.

By the way this field should support a new entry for FCM now.

**Comment by ajsb85** [comment]
Hi, @btry 
We know that the ItemType Operating System is in the GLPI Core.
Maybe you should change the key associtated with the Agent ItemType to the Operating System name key from the GLPI core.
By the way you can configure APNs with FCM.

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
In any case, please put the information requested to the HTML screens.
Thank you in advance.
