### ISSUE TITLE
Pivoting the name of FusionInventory Agent after every request

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#840]
Hi, @flyve-mdm/backend-development 

Why the name changes:
from 
`android-4e024bafab01d943-2018-10-11-13-29-07 `
to
`0123456789ABCDEF_A0:01:32:F7:93:CC`
and sometimes
from
`0123456789ABCDEF_00:78:62:d5:da:87`
to
`android-4e024bafab01d943-2018-10-11-13-29-07`

Could you @Ivans51 and @rafaelje propose the same Agent ID?

Look at the logs:

![image](https://user-images.githubusercontent.com/663460/50258638-d7e30000-0400-11e9-9617-040030f79727.png)

**Comment by btry** [comment]
The name changes because the inventory report don't reports the same name each time the inventory is collected. 

show me the URL of the page I want to check the related itemtype.

**Comment by btry** [comment]
it is deleted.. cannot investigate firther, closing
