### ISSUE TITLE
Messages of the commands for FCM and MQTT

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#841]
Hi, @Naylin15 
Could you change the name of the tab to from "MQTT subscriber" to **Messages**
Because this screen shows messages of the commands for FCM and MQTT.
Remaining rename the internal code to-be generic name for FCM and MQTT, It takes time /cc @DIOHz0r 

![image](https://user-images.githubusercontent.com/663460/50260313-b20d2980-0407-11e9-8653-094924d9f49e.png)

**Comment by DIOHz0r** [comment]
Hi,

This tab doesn't show messages from FCM at this moment this is a report only for MQTT so no FCM relations here.
