### ISSUE TITLE
Rename header Date of the MQTT suscribers tab

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#842]
Hi, @DIOHz0r 

If you keep the same message and you update the date. You should rename header from "Date" to "Last update"

![image](https://user-images.githubusercontent.com/663460/50260510-90f90880-0408-11e9-999d-dc04f4d0104a.png)

**Comment by DIOHz0r** [comment]
Hi,

There is not an update action here, this is a log report so the messages aren't kept, it shows chronologically the actions made in the MQTT broker for the notifiable item (agent/fleet).
