### ISSUE TITLE
Deleting task to remove an application

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#843]
Hi, @flyve-mdm/backend-development 

How I can purge this pending task?
The task tab does not show any task to delete.

![image](https://user-images.githubusercontent.com/663460/50260738-99057800-0409-11e9-8c3d-90c07a9d68e8.png)

**Comment by btry** [comment]
Hi

you can remove this by removing the related task. It may be applied at device level, or at fleet level.

**Comment by ajsb85** [comment]
Done, thank you.
