### ISSUE TITLE
Periodic geolocation

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#847]
Send a task to the device to send the geolocation with intervals of time customized.

**Comment by DIOHz0r** [comment]
This is a duplicated issue already done at https://github.com/flyve-mdm/glpi-plugin/issues/408 and not yet implemented in the agent

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
Nice, do you know where is the PR merged in the plugin and the task pending in the MDM Agent?
To add those links as references for this issue.

**Comment by DIOHz0r** [comment]
The PR/issues related could be found from here https://github.com/flyve-mdm/android-mdm-agent/issues/339
