### ISSUE TITLE
Invitation Logs

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#848]
Hi, @flyve-mdm/backend-development 

Where is the invitation logs?
Why no delete the Sub ItemType InvitationLogs and add the Historical tab to show these kind of logs?

![image](https://user-images.githubusercontent.com/663460/50286120-aa2ca400-045e-11e9-902d-c73c677f0f2c.png)

**Comment by btry** [comment]
An invitation is created, used then expired. 

It is not really necessary to log its life as it does not change in a very useful manner. That said, I think we could improve a bit the main (and only) tab.

**Comment by ajsb85** [comment]
Hi, @btry 
But the actual InvitationLogs should show these cases and the date in each case:

- The invitation has been sent
- The invitation was used
- The invitation expired
- The invitation has been re-sent
- The agent that want to use a invitation expired
- The agent that use the invitation

**Comment by btry** [comment]
we may ad a tab for the invitation log. Is is really useful or urgent ? The debug mode allows to show the error on the device itself, and the experience shows that users are interested only by the latest event when finding why an enrollment fails.

**Comment by ajsb85** [comment]
Hi. @btry 
I agree with the interest of the users; plan it for now or later, as you can.

**Comment by btry** [comment]
pr in progress

![image](https://user-images.githubusercontent.com/14139801/50291100-e0bdeb00-046d-11e9-8484-c971e4da68ab.png)

**Comment by DIOHz0r** [comment]
@btry, It would be nice if the expiration option is enabled make a visual mark on that interface, for instance, a crossed out on the date or an exclamation mark explaining the invalidity of the date.

**Comment by btry** [comment]
i'm thinking about that right now. This is a bit tricky : 
an invitation is invalid if the datetime is < now() or if has the status "done". I want to avoid to compute from a cron tasl the update of a computed column... Maybe post_getFromDB() will solve that along with some hook for the search engine. The problem is that this will make the coed messy. And i don"t like mess
