### ISSUE TITLE
Grammar/typo issues

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#857]
Hi,  @Naylin15 

Please fix these grammar/typo issues in the GLPI UI.
Below each image, I added the correct expression to show.
Mostly case sensitive issues.

![image](https://user-images.githubusercontent.com/663460/50314981-37004d80-04b1-11e9-90a3-8fd9bc09b166.png)

- [x] Add document types

![image](https://user-images.githubusercontent.com/663460/50315028-67e08280-04b1-11e9-98bc-71cf8a3ff266.png)

- [x] MQTT broker cipher suite
- SSL certificate server for MQTT clients

( ask and remove about the field and button called "test")

![image](https://user-images.githubusercontent.com/663460/50315286-724f4c00-04b2-11e9-8f71-cd8625d508e3.png)

- [x] File size

![image](https://user-images.githubusercontent.com/663460/50315304-885d0c80-04b2-11e9-8c25-971e6e6cff2e.png)

- [x] File size

![image](https://user-images.githubusercontent.com/663460/50315508-67e18200-04b3-11e9-87f1-051afca3a577.png)

- [x] Apply a policy

![image](https://user-images.githubusercontent.com/663460/50315538-7cbe1580-04b3-11e9-8aed-7f829c38f100.png)

- [ ] Use TLS

![image](https://user-images.githubusercontent.com/663460/50315777-5c428b00-04b4-11e9-93c8-faae5044a912.png)

- [x] Name

![image](https://user-images.githubusercontent.com/663460/50324027-1b12a100-04dd-11e9-9f95-f997e382d98f.png)

- [ ] queue notification

![image](https://user-images.githubusercontent.com/663460/50324055-3ed5e700-04dd-11e9-9439-cbf77f0cca81.png)

- [x] Cron job

![image](https://user-images.githubusercontent.com/663460/50324080-51502080-04dd-11e9-8e19-32b9e3cf47a6.png)

- [x] FusionInventory configuration

![image](https://user-images.githubusercontent.com/663460/50324151-a855f580-04dd-11e9-989f-1f63e660c5f4.png)

- [x] Server configuration

![image](https://user-images.githubusercontent.com/663460/50324155-b4da4e00-04dd-11e9-84d2-88f44ac5c0b3.png)

- [x] Add document types
- [x] Document types

**Comment by Naylin15** [comment]
Hi, 

I couldn't find this string, use TLS
For queuednotification, I won't change it since this is the name of the GLPI notification
