### ISSUE TITLE
I cannot delete fleets if the policy not found

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#865]
Hi, @DIOHz0r 
I cannot delete fleets if the policy not found

![image](https://user-images.githubusercontent.com/663460/50720331-50a5b580-10ab-11e9-94f1-afca6aa51f11.png)

Reference: https://dev.flyve.org/glpi/plugins/flyvemdm/front/fleet.php

**Comment by btry** [comment]
I think that you tried to delete a not managed fleet. At least one error is normal.

**Comment by btry** [comment]
Problem solved by above PR. closing.
