### ISSUE TITLE
Adding an agent manually

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#866]
Hi, @DIOHz0r 

I cannot add an agent manually.

- I cannot add "Notification type"
- I cannot add "MDM type"

And finally the notification show the message: "Unable to find a enrollment method"

![image](https://user-images.githubusercontent.com/663460/50720987-f828e500-10b7-11e9-8901-0a42ba010227.png)

**Comment by btry** [comment]
Hi

This is by design. We only can create an agent when enrolling a device.
