### ISSUE TITLE
Recreating guest profile

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-plugin#867]
Hi, @DIOHz0r 

I remove the guest profile, and I create again, but when I request the full session.
The value `plugin_flyvemdm_guest_profiles_id` shows the past guest user profile.

Any way to fix it?

**Comment by btry** [comment]
If you ignore the comment and delete it anyway, then pray :)

We might prevent deletin thanks to hooks. But this is not a priority for now

**Comment by btry** [comment]
support/2.0 branch created with a fix: da525f536e124a6414ad23563559fb4556467035

closing
