### ISSUE TITLE
GLPI Same Brand The model lists two different recorded devices as a single device.

### ISSUE THREAD

**Issue by Greenstonetr** [flyve-mdm/glpi-plugin#875]
GLPI shows a single device when the same brand and model device is added. For example:
Samsung Sm P600 is adding 2 different devices. But under GLPI Computer, one looks at SM P600.
![flyvelist](https://user-images.githubusercontent.com/43892434/51985269-8f623c00-24ae-11e9-831f-59492c05d3b2.PNG)
![glpi_list](https://user-images.githubusercontent.com/43892434/51985282-9426f000-24ae-11e9-8a55-42ea2a769c3c.PNG)

**Comment by btry** [comment]
Hi

I think that the import rules in Fusion Inventory are not configured to work well for your devices. Maybe the inventory of the 2nd device matches the 1st device (already enrolled).

I suggest you get the inventory XML from both devices with our inventory agent for Android and import them manually in Fusion Inventory to fond how the import rules are executed.

**Comment by Greenstonetr** [comment]
Change Fusion Inventory Import Rules  SOLVED
