### ISSUE TITLE
Documentation review UX/UI

### ISSUE THREAD

**Issue by jguerere** [flyve-mdm/glpi-plugin#884]
Getting used to the product information:

- [x] GLPI documentation review 
- [x] MDM documentation review
- [x] Flyve-mdm documentation review

**Comment by saidmar19** [comment]
This task allows the UX team to understand the objectives and purposes of the plugin. Additionally, give a vision of the styles currently managed and their points of improvement. Understand to whom an application is directed, in which situations it is used and other details of the context of use allow important decisions to be made on the subject of design. @ajsb85
