### ISSUE TITLE
Device Agent status Online

### ISSUE THREAD

**Issue by praneshjan** [flyve-mdm/glpi-plugin#913]
I have configured flyve MDM agent in my device and if I switch off my device it is still showing online status. Is there anythings that need to be enable in my flyve mdm plugin.

**Comment by stonebuzz** [comment]
Hi @praneshjan 

I think the problem is with the MDM agent, 
could you open an issue out on the right repo ?
-> https://github.com/flyve-mdm/android-mdm-agent

Best regards
